# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Adding the node orb
orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run upgrade-all
          name: Upgrade
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run package
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-granada-workflow:
    jobs:
      - build-and-test
