{
 "title": "Granada Api Overview",
 "description": "An overview of various HTTP statistics about how the api is performing",
 "tags": [
  "Granada",
  "http",
  "server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket,namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket{namespace=\"$namespace\", service=\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS By Endpoint",
   "type": "barchart",
   "description": "The RPS on each endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(template) (rate(incoming_route_duration_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Distribution",
   "type": "barchart",
   "description": "The distribution of status codes by endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(template, status) (increase(route_response_status_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Response Time",
   "type": "heatmap",
   "description": "A heatmap showing response time averages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_incoming_request_duration_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Response Time",
   "type": "timeseries",
   "description": "A heatmap showing response time averages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(incoming_route_duration_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}