{
 "title": "Granada HTTP",
 "description": "An overview of various HTTP statistics about how the server is performing",
 "tags": [
  "Granada",
  "http",
  "server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket,namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(http_incoming_request_duration_bucket{namespace=\"$namespace\", service=\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http Response Time",
   "type": "heatmap",
   "description": "A heatmap showing response time averages",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_incoming_request_duration_bucket{service=~\"$service\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Response Time",
   "type": "timeseries",
   "description": "A heatmap showing response time averages",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_incoming_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_incoming_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_incoming_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_incoming_request_duration_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Http Status Distribution",
   "type": "piechart",
   "description": "The distribution of HTTP Status Codes",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_response_status_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipeline Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests",
   "type": "stat",
   "description": "The rate of incoming HTTP Requests",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_incoming_request_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Actions",
   "type": "stat",
   "description": "The rate of pipeline stage invocations",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_pipeline_stage_invocations_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "stat",
   "description": "The rate of backpressure events in the pipeline",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_pipeline_backpressure_events_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Invocations By Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(stage) (rate(http_pipeline_stage_invocations_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure By Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "sum by(stage) (rate(http_pipeline_backpressure_events_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_incoming_request_received_total[$__rate_interval]))",
     "legendFormat": "Incoming RPS"
    }
   ]
  },
  {
   "title": "Request Delay P95",
   "type": "stat",
   "description": "The amount of time a request has to wait before being handled",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(request_delay_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of request timeouts before handling",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_timeout_counter_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}