{
 "title": "Granada NodeJS Overview",
 "description": "This is a high level view of how the NodeJS environment is working for Granada applications that have enabled metrics.",
 "tags": [
  "NodeJS",
  "Granada"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(event_loop_utilization,namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(event_loop_utilization{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(event_loop_utilization{service=\"$service\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Event Loop",
   "type": "timeseries",
   "description": "Measures the average utilization for each namespace/service combination based on the variables chosen in the dashboard",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(namespace, service) (event_loop_utilization{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap By Space",
   "type": "piechart",
   "description": "Shows the current distribution of heap size by space",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "GC Distribution",
   "type": "piechart",
   "description": "Shows the distribution of time in each GC cycle for the current environment",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (idelta(node_gc_duration_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Handles",
   "type": "gauge",
   "description": "The total number of memory handles that are active.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, service) (node_memory_handles{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Heap Used",
   "type": "barchart",
   "description": "The amount of heap space that is currently in use",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(space) (heap_space_used_size{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Totals",
   "type": "barchart",
   "description": "The amount of space available that isn't in use",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(space) (heap_space_available_size{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"} + heap_space_used_size{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Available",
   "type": "barchart",
   "description": "The amount of space available that isn't in use",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(space) (heap_space_available_size{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "barchart",
   "description": "The amount of time spent in each GC collection kind",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(kind) (increase(node_gc_duration_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}